name: build with conda

on: [push]

env:
  TORCH: "1.8.1"
  CONDA_PREFIX: /usr/share/miniconda

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [3.7, 3.8, 3.9]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
          access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.version }}
        conda-channels: anaconda

    - name: install dependencies
      run: |
        # torch==1.8.1 dependencies
        conda install scipy rdkit pytorch==${TORCH} torchvision cpuonly
        pip install "gpytorch<=1.5.1"  # TODO: Remove when switching to pytorch >=1.9
        pip install dgl

        # torch-geometric dependencies
        pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH}+cpu.html
        pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-${TORCH}+cpu.html
        pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/torch-${TORCH}+cpu.html
        pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/torch-${TORCH}+cpu.html

        # The package
        pip install .[test,doc]

    - name: Conda info
      run: conda info

    - name: Conda list
      run: conda list -n base

    - name: Test with pytest
      run: |
        pytest

    - name: coverage
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        name: codecov-umbrella
